### ISSUE TITLE
Post processing issue that occurred during MobileNetV2 + SSD Network conversion

### ISSUE THREAD

**Issue by LilaK** [VeriSilicon/acuity-models#12]
I am currently converting a network with SSD added to a MobileNetV2-based network.

In post-processing the SSD processing result, the answer is that it can only be operated on the CPU, 

but

In the case of the process I will use in post-processing, I confirmed that it consists only of layers that can be sufficiently processed on the network.

May I know if there is a function to add post processing inside? 
Or can you give me some information on how to use the post process related files exactly?
(ex. postprocess.yml or postprocess.py)

**Comment by geneyoung** [comment]
please refer to the newest user guide to add post process such as data convert,transpose, resize etc. into network
