### ISSUE TITLE
'Normal' PTQ algorithm 

### ISSUE THREAD

**Issue by macsmy** [VeriSilicon/acuity-models#13]
Hi!
I have a question related to Post Training Quantization. What does the 'normal' algorithm mean? What is the difference between 'normal' and 'moving_average' algorithm? 
With regards, 
Maciej

**Comment by geneyoung** [comment]
Both 'normal' and 'moving_average' are calibrating algorithm to decide how to collecting and arrange set of quantize parameters into one quantize parameter. 
'normal': get max of all quantize parameters's max,  get min of all quantize parameters's min
'moving_average': Weighted Average to process quantize parameters
