### ISSUE TITLE
目前提供支持的模型大部分是tensorflow的？

### ISSUE THREAD

**Issue by RUIXUEZHAOFENGNIAN** [VeriSilicon/acuity-models#14]
希望能提供更多pytorch的预训练模型和onnx格式的权重文件

**Comment by geneyoung** [comment]
Acuity supports pre-trained model from NN frameworks such as Tensorflow/ONNX/Pytorch, please get the newest version to have a try. see https://github.com/VeriSilicon/acuitylite
