### ISSUE TITLE
undefined symbol: PyFPE_jbuf

### ISSUE THREAD

**Issue by wzf19947** [VeriSilicon/acuity-models#3]
After I installed the ACUITY5.16.3-cpu successfully，when I want to translate a model like lenet, it happens this problem----ImportError: /home/ubuntu/anaconda3/lib/python3.5/site-packages/acuitylib/acuitylog.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf
what's that mean? or how to solve it?

**Comment by geneyoung** [comment]
Could you please try to use default python 3.5 environment in ubuntu to try again, instead of anaconda3? 
Meanwhile, please make sure all python packages that required by Acuity is installed.
We support Ubuntu 16.04(python3.5), Ubuntu 18.04(python 3.6) so far.
