### ISSUE TITLE
Add/Mul/Pow op failed

### ISSUE THREAD

**Issue by XinnWang** [VeriSilicon/acuity-models#4]
According to the ONNX-ACUITY operations mapping in Neural Network Layer and Operation Support Guide (ref. v1.17-20200623),  Add/Mul/Pow is already supported. but i cannot use them.

 i use the following code to generate onnx model.

```
import numpy as np
import torch

class TestNet(torch.nn.Module):
    def __init__(self):
        super(TestNet, self).__init__()
    def forward(self, x):
        # x = torch.pow(x,2)
        # x = torch.add(x,x)
        x = torch.mul(x,x)
        return x

if __name__ == '__main__':
    model = TestNet()
    dummy_input = torch.randn(1, 1, 360, 640)
    torch.onnx.export(model, dummy_input, "test.onnx")
```

i use the convert_onnx tool inside aml_npu_skd_6.4.3, but failed.
![image](https://user-images.githubusercontent.com/5515327/113673164-36743b00-96eb-11eb-8d6d-0ea415a7b897.png)

My env:
- python 3.6.9
- torch 1.2.0

Any helps or suggestions? Thanks.

**Comment by geneyoung** [comment]
Which version of Acuity you used? 
I can import the onnx model generated by your provided script on Acuity 5.14.x, 5.21.x

**Comment by XinnWang** [comment]
@geneyoung My Acuity is provided by Amlogic NPU SDK 6.4.3, which is released last year. i cannot find the version of it but i think it is out of date. Where can i download the new version of Acuity? Can you share the Acuity 5.14.x or 5.21.x with me? Thanks.

**Comment by geneyoung** [comment]
@XinnWang Just tried unbuntu16.04 binary package of Acuity in NPU SDK 6.4.3, I can also import the model generated by the scripts you provided. 

My env:
python 3.5.2
torch 1.2.0

can you c
