### ISSUE TITLE
YoloV5

### ISSUE THREAD

**Issue by fangichao** [VeriSilicon/acuity-models#7]
when i import yolov5 model in step 1, it raise pytorch verison error , yolov5 model trained by torch=1.9, but the tool's requrements.txt requires torch==1.2.0。 can i update torch?

**Comment by geneyoung** [comment]
Please refer to https://github.com/ultralytics/yolov5/releases/ to convert pytorch model to onnx model, and then use "pegasus import onnx ..." to import this newly generated onnx model.
